EXT_DIR = ../fuior_compiler/native_extension

SOURCES = \
	main.c \
	$(EXT_DIR)/include/tree_sitter/src/lib.c \
	$(EXT_DIR)/src/fuior.c \
	$(EXT_DIR)/include/parser.c

HEADERS = $(EXT_DIR)/src/fuior.h

CFLAGS = -I. -I$(EXT_DIR)/src -I$(EXT_DIR)/include

build/Windows/fuior.exe: $(SOURCES) $(HEADERS)
	mkdir build\\Windows
	$(CC) /Fo: build/ /Fe: $@ $(SOURCES) $(CFLAGS)
